{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"spotify_songs\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1177.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "spotify_songs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "track_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aec4d57e-6147-4b7f-99ac-e0ced920d66d",
            "sourceColumn": "track_name",
            "summarizeBy": "none"
          },
          {
            "name": "album",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7888213f-de28-4634-b43c-d730770c0feb",
            "sourceColumn": "album",
            "summarizeBy": "none"
          },
          {
            "name": "album_release",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77412d3d-48e4-4c20-8712-960000abb0c3",
            "sourceColumn": "album_release",
            "summarizeBy": "sum"
          },
          {
            "name": "artist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50f825a2-4edf-4789-a265-93ee8563fe08",
            "sourceColumn": "artist",
            "summarizeBy": "none"
          },
          {
            "name": "popularity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72bf3317-ebfe-4803-9c38-2af29abb27f8",
            "sourceColumn": "popularity",
            "summarizeBy": "sum"
          },
          {
            "name": "genres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6391f7a1-a3c2-42e5-bcec-483eff51469d",
            "sourceColumn": "genres",
            "summarizeBy": "none"
          },
          {
            "name": "playlist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec67a2ad-6d51-4fe6-b4c3-93d2d58509f5",
            "sourceColumn": "playlist",
            "summarizeBy": "none"
          },
          {
            "name": "duration_sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "4eca2e80-36bd-4605-b3bf-f421b09d11b8",
            "sourceColumn": "duration_sec",
            "summarizeBy": "sum"
          },
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "[album_release]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fe3a90a6-1484-4f7f-a05e-8545df0e288c",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "df68bf99-5230-46dd-925e-f609af34cb04",
        "partitions": [
          {
            "name": "spotify_songs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Admin\\Desktop\\SBCodes\\Python\\Data Analysis\\SpotifySongsAnalysis\\spotify_songs.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"track_name\", type text}, {\"album\", type text}, {\"album_release\", type date}, {\"artist\", type text}, {\"popularity\", Int64.Type}, {\"genres\", type text}, {\"playlist\", type text}, {\"duration_sec\", type number}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"album_release\", Order.Ascending}}),",
                "    #\"Extracted Year\" = Table.TransformColumns(#\"Sorted Rows\",{{\"album_release\", Date.Year, Int64.Type}})",
                "in",
                "    #\"Extracted Year\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_178a79e1-c278-45b4-a229-33a7594c59fa",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0df7d2e7-a878-49d9-9734-44f44ee1e1d6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ddde7f95-90b6-4def-a4f8-04781b44743e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "833362f8-9262-4967-9376-e07d939984a5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "99353c33-b386-4113-abdf-009ab0bf1e7a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a9bcfbe7-0143-4d71-8180-b21f3702924c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "42a90e20-5ea7-485b-a478-72cb6a465972",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "41c92ee0-c738-4c35-92c5-4ec75ccf7838",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "03110e2c-ccc9-4ea2-ac78-ae9d60708b3d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cd52f2eb-dac3-4118-a79f-7a64af8c3da7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c793f882-cc04-49f6-86be-3c8953fc98bb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "48297047-7668-4041-963b-5fdd5c9487c4",
                "ordinal": 3
              }
            ],
            "lineageTag": "daf4aa58-b821-425b-b58a-7a8bd816027a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f2916951-22f1-476a-a1ab-7ef36101a9e9",
        "partitions": [
          {
            "name": "DateTableTemplate_178a79e1-c278-45b4-a229-33a7594c59fa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}